version: "3"
services:
#  nginx:
#    image: nginx:stable
#    container_name: nginx
#    volumes:
#      - "/home/mvazquez/nginx/conf/default.conf:/etc/nginx/conf.d/default.conf"
#    ports:
#      - "80:8081"
#    depends_on:
#      - "varnish"
  varnish:
    image: varnish:stable
    container_name: varnish
    volumes:
      - /home/mvazquez/varnish/cfg/default.vcl:/etc/varnish/default.vcl
    ports:
      - "80:80"
    tmpfs:
      - /var/lib/varnish:exec
    environment:  
      - VARNISH_SIZE=2G  
    command: "-p default_keep=300"
    depends_on:
      - "httpd" 
  httpd:
    image: wordpress:php8.0
    container_name: httpd
    environment:
      WORDPRESS_DB_HOST: mysqld
      WORDPRESS_DB_USER: wp_user
      WORDPRESS_DB_NAME: wp
      WORDPRESS_DB_PASSWORD: Asurb4n1p4l.wp
      WORDPRESS_TABLE_PREFIX: wp
      WORDPRESS_DEBUG: 1
    volumes:
      - /home/mvazquez/content:/var/www/html/wp-content/uploads
      - /home/mvazquez/backup:/tmp/backup
    depends_on:
      - "mysqld"
#    ports:
#      - "8081:80"
  mysqld:
    image: mariadb
    container_name: mysqld
    environment:
      MYSQL_ROOT_PASSWORD: Asurb4n1p4l.mysql
      MYSQL_DATABASE: wp
      MYSQL_USER: wp_user
      MYSQL_PASSWORD: Asurb4n1p4l.wp
    volumes:
      - /home/mvazquez/mysqld:/var/lib/mysql
      - /home/mvazquez/backup:/tmp/backup
#    ports:
#      - "3306:3306"
